name: Bearer Cloud

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan
        id: scan
        uses: bearer/bearer-action@v2
        with:
          diff: ${{ github.event.repository.default_branch != github.ref_name }}
          api-key: ${{ secrets.BEARER_CLOUD_TOKEN }}
